new helm release script

diff --git a/release-helm-chart b/release-helm-chart
--- a/release-helm-chart
+++ b/release-helm-chart
@@ -11,21 +11,24 @@
 usage() {
     cat<<EOF
 usage:
- if on master branch: release pre|rc [<chart>]
-if on release branch: release major|minor|patch|pre [<chart>]
+if on master  branch: release pre|rc [chart]
+if on release branch: release major|minor|patch|pre [chart]
 
 where:
-  <chart> is the name of the chart and its directory, unless it's "."
-    * if "." is given, chart name is assumed to be the name of the directory containing ".", otherwise
-    * the default value is the only dirname in this directory that doesn't start with ".", unless there are multiple
+  chart is the name of the chart and its directory, unless it is ".."
+    * if ".." is given, chart name is assumed to be the name of the directory containing the current working directory, otherwise
+    * the default value is the only directory name in this directory that does not start with ".", unless there are multiple
+
+optional supported environment variables:
+
+variable                  description
+--------                  -----------
+ORIGIN                    name of git remote, default 'origin'
+MASTER                    name of master branch, default 'master'
+CHART_DIR                 name of chart directory, default derived from given chart name
+CHART_FILE                name of chart file, default derived from chart directory
 EOF
 }
-
-if [ -n "$TEST" ]; then ECHO=echo; fi
-if [ -n "$DBG" ]; then set -x; fi
-
-ORIGIN=${ORIGIN:-origin}
-MASTER=${MASTER:-master}
 
 RELEASE_LEVEL="$1"
 case "$RELEASE_LEVEL" in
@@ -37,20 +40,23 @@ case "$RELEASE_LEVEL" in
     exit 0
     ;;
   *)
-    echo "ERROR: Specify release level of 'pre', 'patch', 'minor', 'major', or 'rc'" >&2
+    if [ -n "$1" ]; then
+      echo "ERROR: specify release level of 'pre', 'patch', 'minor', 'major', or 'rc'" >&2
+    fi
     usage
     exit 1
     ;;
 esac
 
 CHART_NAME=${2%/} # drop trailing slash if it's there
-if [ "$CHART_NAME" == '.' ]; then
+if [ "$CHART_NAME" == '..' ]; then
   CHART_NAME="$(basename $(pwd))"
   CHART_NAME="${CHART_NAME%/}"
-  echo "INFO: using $CHART_NAME as chart name"
-  CHART_DIR=.
-  CHART_FILE="${CHART_FILE:-$CHART_DIR/Chart.yaml}"
-elif [ -z "$CHART_NAME" ]; then
+  CHART_DIR=${CHART_DIR:-.}
+elif [ -n "$CHART_NAME" ]; then
+  CHART_NAME="${CHART_NAME%/}"
+  CHART_DIR="${CHART_DIR:-$CHART_NAME}"
+else # no chart name given; see if there is a single directory in pwd that doesn't start with "."
   NON_DOT_DIRS="$(find . -type d -depth 1 | sed 's|^\./||g' | grep -v '^\.')" # directories that don't start with '.'
   if [ $(echo "$NON_DOT_DIRS" | wc -l | xargs) == 1 ]; then # we'll assume this sole dir is chart dir
     CHART_NAME="${NON_DOT_DIRS%/}"
@@ -61,42 +67,71 @@ elif [ -z "$CHART_NAME" ]; then
     exit 1
   fi
   CHART_DIR="${CHART_DIR:-$CHART_NAME}"
-  CHART_DIR="${CHART_DIR%/}"
-  CHART_FILE="${CHART_FILE:-$CHART_DIR/Chart.yaml}"
 fi
+CHART_DIR="${CHART_DIR%/}"
+CHART_FILE="${CHART_FILE:-$CHART_DIR/Chart.yaml}"
+echo "INFO: using chart name:      $CHART_NAME"
+echo "INFO: using chart directory: $CHART_DIR"
+echo "INFO: using chart file:      $CHART_FILE"
+
+getVersion() {
+  cat "$CHART_FILE" | docker run --rm -i matthewadams12/ymlx this.version
+}
+
+# usage: setVersion version
+setVersion() {
+  V=$1
+  CHART_CONTENT="$(cat $CHART_FILE)"
+  echo -n "$CHART_CONTENT" \
+    | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$V'; return it; }" \
+    > $CHART_FILE
+  echo "INFO: set 'version' attribute in $CHART_file to $V"
+}
+
+if [ -n "$TEST" ]; then ECHO=echo; fi
+if [ -n "$DBG" ]; then set -x; fi
+
+ORIGIN=${ORIGIN:-origin}
+MASTER=${MASTER:-master}
+
+echo "INFO: checking required preconditions"
 
 git pull > /dev/null 2>&1
 
 if ! git diff --exit-code --no-patch > /dev/null 2>&1; then
-  echo 'ERROR: You have modified tracked files; only release from clean directories!' >&2
+  echo 'ERROR: you have modified tracked files; only release from clean directories!' >&2
   exit 3
+else
+  echo 'INFO: no modified tracked files'
 fi
 
 if ! git diff --cached --exit-code --no-patch > /dev/null 2>&1; then
-  echo 'ERROR: You have cached modified tracked files; only release from clean directories!' >&2
+  echo 'ERROR: you have cached modified tracked files; only release from clean directories!' >&2
   exit 3
+else
+  echo 'INFO: no cached modified tracked files'
 fi
 
 if [ -n "$(git status -s)" ]; then
   echo 'ERROR: You have unignored untracked files; only release from clean directories!' >&2
   exit 3
-fi
-
-VERSION="$(cat $CHART_FILE | docker run --rm -i matthewadams12/ymlx this.version)"
-if [[ ! "$VERSION" =~ \-(pre|rc)\.[0-9]{1,}$ ]]; then
-  echo 'ERROR: repository is in an inconsistent state: version does NOT end in a prerelease suffix!' >&2
-  exit 3
+else
+  echo 'INFO: no unignored untracked files'
 fi
 
 BRANCH="$(git status | head -n 1 | awk '{ print $3 }')"
 if [[ ! "$BRANCH" =~ ^(master|v[0-9]{1,}\.[0-9]{1,})$ ]]; then # it is not a master or a release branch
-  echo 'ERROR: You can only release from the master branch or release branches (vmajor.minor)!' >&2
+  echo 'ERROR: you can only release from the master branch or release branches (vmajor.minor)!' >&2
   exit 3
+else
+  echo "INFO: on branch $BRANCH, from which releases are allowed"
 fi
 
 if ! git diff --exit-code -no-patch $BRANCH $ORIGIN/$BRANCH > /dev/null 2>&1; then
   echo "ERROR: Local branch $BRANCH differs from remote branch $ORIGIN/$BRANCH" >&2
   exit 3
+else
+  echo "INFO: no differences between local & remote branch $BRANCH"
 fi
 
 if [ "$BRANCH" == "$MASTER" ]; then
@@ -105,7 +140,7 @@ if [ "$BRANCH" == "$MASTER" ]; then
       # ok
       ;;
     *)
-      echo "ERROR: Only 'pre' or 'rc' releases are permitted from the $MASTER branch." >&2
+      echo "ERROR: only 'pre' or 'rc' releases are permitted from the $MASTER branch." >&2
       exit 6
       ;;
   esac
@@ -115,16 +150,60 @@ else # this is a release branch
         # ok
         ;;
       *)
-        echo "ERROR: Only 'pre', 'patch', 'minor', or 'major' releases are permitted from a release branch." >&2
+        echo "ERROR: only 'rc', 'patch', 'minor', or 'major' releases are permitted from a release branch." >&2
         exit 7
         ;;
   esac
 fi
 
-if [ "$BRANCH" == "$MASTER" ]; then
+echo "INFO: ok to proceed with $RELEASE_LEVEL from branch $BRANCH"
+
+echo "INFO: determining current version from $CHART_FILE"
+
+VERSION="$(getVersion)"
+if [[ ! "$VERSION" =~ \-(pre|rc)\.[0-9]{1,}$ ]]; then
+  echo 'ERROR: repository is in an inconsistent state: version does NOT end in a prerelease suffix!' >&2
+  exit 3
+fi
+
+echo "INFO: current version is $VERSION"
+
+# usage: apply message [tag [remote branch]]
+applyChanges() {
+  git add . > /dev/null 2>&1
+  git commit -m "$1" > /dev/null 2>&1
+  echo "INFO: committed changes with message: $1"
+
+  MSG="INFO: pushed commits"
+
+  if [ -n "$2" ]; then
+    git tag "$2" > /dev/null 2>&1
+    echo "INFO: tagged $2"
+    MSG="$MSG & tags"
+  fi
+
+  SET_UPSTREAM_ARGS=
+  if [ -n "$3" ] && [ -n "$4" ]; then
+    SET_UPSTREAM_ARGS="-u $3 $4"
+    MSG="$MSG & set tracked upstream to $3/$4"
+  fi
+
+  if [ -n "$SET_UPSTREAM_ARGS" ]; then
+    git push $SET_UPSTREAM_ARGS > /dev/null 2>&1
+    git push --tags > /dev/null 2>&1
+  else
+    git push --follow-tags > /dev/null 2>&1
+  fi
+
+  echo "$MSG"
+}
+
+if [ "$BRANCH" == "$MASTER" ]; then # this will be either an rc, resulting in a new release branch, or a pre
   if [[ ! "$VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})\.0\-pre\.([0-9]{1,})$ ]]; then
-    echo "ERROR: The version does not match the format of major.minor.0-pre.n required in the $MASTER branch." >&2
+    echo "ERROR: the version does not match the format of major.minor.0-pre.n required in the $MASTER branch." >&2
     exit 8
+  else
+    echo "INFO: version $VERSION matches expected format for branch $BRANCH"
   fi
 
   # create release branch
@@ -140,69 +219,49 @@ if [ "$BRANCH" == "$MASTER" ]; then
 
       NEW_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.0-rc.0"
 
-      CHART_CONTENT="$(cat $CHART_FILE)"
-      echo -n "$CHART_CONTENT" \
-        | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEW_RELEASE_BRANCH_VERSION'; return it; }" \
-        > $CHART_FILE
+      setVersion $NEW_RELEASE_BRANCH_VERSION
 
-      git add . > /dev/null 2>&1
-      git commit -m "release $NEW_RELEASE_BRANCH_VERSION" > /dev/null 2>&1
-      git tag "v$NEW_RELEASE_BRANCH_VERSION" > /dev/null 2>&1
-      git push -u $ORIGIN $NEW_RELEASE_BRANCH > /dev/null 2>&1
-      git push --tags > /dev/null 2>&1
+      applyChanges "release $NEW_RELEASE_BRANCH_VERSION" $NEW_RELEASE_BRANCH_VERSION $ORIGIN $NEW_RELEASE_BRANCH
+      echo "INFO: created release branch $NEW_RELEASE_BRANCH and tagged $NEW_RELEASE_BRANCH_VERSION for release"
 
       # return to master branch
       git checkout $MASTER > /dev/null 2>&1
+      echo "INFO: checked out $MASTER"
+
       git cherry-pick $NEW_RELEASE_BRANCH > /dev/null 2>&1 # cherry pick from release branch to get release candidate commit in master
+      echo "INFO: cherry-picked $NEW_RELEASE_BRANCH rc commit into $MASTER"
+
       # advance master version
       NEXT_VERSION="$MAJOR.$(($MINOR+1)).0-pre.0"
 
-      CHART_CONTENT="$(cat $CHART_FILE)"
-      echo -n "$CHART_CONTENT" \
-        | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_VERSION'; return it; }" \
-        > $CHART_FILE
+      setVersion $NEXT_VERSION $DOCKER_BUILD_STEP_NAMES
 
-      git add . > /dev/null 2>&1
-      git commit -m "bump to $NEXT_VERSION [skip ci]" > /dev/null 2>&1
-      git push > /dev/null 2>&1
+      applyChanges "bump to $NEXT_VERSION [skip ci]"
 
       # return to release branch & prepare for next prerelease
       git checkout $NEW_RELEASE_BRANCH > /dev/null 2>&1
+      echo "INFO: checked out $NEW_RELEASE_BRANCH"
+
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.0-rc.1"
 
-      CHART_CONTENT="$(cat $CHART_FILE)"
-      echo -n "$CHART_CONTENT" \
-        | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
-        > $CHART_FILE
+      setVersion $NEXT_RELEASE_BRANCH_VERSION $DOCKER_BUILD_STEP_NAMES
 
-      git add . > /dev/null 2>&1
-      git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]" > /dev/null 2>&1
-      git push > /dev/null 2>&1
+      applyChanges "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]"
 
-      echo "created release branch $NEW_RELEASE_BRANCH and tagged $NEW_RELEASE_BRANCH_VERSION for release"
       exit 0
       ;;
 
   pre)
-      if git log -1 --pretty=%s | grep -q '\[skip ci\]'; then
-        # force empty commit so that tag doesn't point at a "[skip ci]" commit
-        git commit --allow-empty -m 'trigger ci' > /dev/null 2>&1
-      fi
+      setVersion $VERSION
 
-      git tag "v$VERSION" > /dev/null 2>&1
-      RELEASED_VERSION="$VERSION"
+      applyChanges "release $VERSION" $VERSION
+
       NEXT_VERSION=$MAJOR.$MINOR.$PATCH-pre.$((PRE+1))
 
-      CHART_CONTENT="$(cat $CHART_FILE)"
-      echo -n "$CHART_CONTENT" \
-        | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_VERSION'; return it; }" \
-        > $CHART_FILE
+      setVersion $NEXT_VERSION
 
-      git add . > /dev/null 2>&1
-      git commit -m "bump to $NEXT_VERSION [skip ci]" > /dev/null 2>&1
-      git push > /dev/null 2>&1
-      git push --tags > /dev/null 2>&1
-      echo "tagged $RELEASED_VERSION for release"
+      applyChanges "bump to $NEXT_VERSION [skip ci]"
+
       exit 0
       ;;
   esac
@@ -211,8 +270,10 @@ fi
 # If we get this far, we are releasing something from a release branch.
 
 if [[ ! "$VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})\.([0-9]{1,})\-rc\.([0-9]{1,})$ ]]; then
-  echo "ERROR: The version does not match the format of major.minor.patch-rc.n required in the release branch." >&2
+  echo "ERROR: the version does not match the format of major.minor.patch-rc.n required in the release branch." >&2
   exit 8
+else
+    echo "INFO: version $VERSION matches expected format for branch $BRANCH"
 fi
 MAJOR=${BASH_REMATCH[1]}
 MINOR=${BASH_REMATCH[2]}
@@ -226,69 +287,50 @@ case "$RELEASE_LEVEL" in
     # A major release is the same as a minor release, only that the minor version is 0.
 
     if [ $RELEASE_LEVEL == major ] && [ $MINOR != 0 ]; then
-      echo "ERROR: This branch is not prepared for a major release because the minor version is $MINOR, not 0." >&2
+      echo "ERROR: this branch is not prepared for a major release because the minor version is $MINOR, not 0." >&2
       exit 10
     else
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-rc.0"
     fi
     if [ $RELEASE_LEVEL == minor ] && [ $PATCH != 0 ]; then
-      echo "ERROR: A minor release has already been performed in this release branch; only patch releases are allowed here now." >&2
+      echo "ERROR: a minor release has already been performed in this release branch; only patch releases are allowed here now." >&2
       exit 11
     else
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-rc.0"
     fi
     if [ $RELEASE_LEVEL == patch ] && [ $PATCH == 0 ]; then
-      echo "ERROR: You must release a minor release before releasing a patch in this release branch." >&2
+      echo "ERROR: you must release a minor release before releasing a patch in this release branch." >&2
       exit 12
     else
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.$((PATCH+1))-rc.0"
     fi
 
+    echo "INFO: $RELEASE_LEVEL ok in branch $BRANCH"
+
     RELEASE_VERSION="$MAJOR.$MINOR.$PATCH"
 
-    CHART_CONTENT="$(cat $CHART_FILE)"
-    echo -n "$CHART_CONTENT" \
-      | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$RELEASE_VERSION'; return it; }" \
-      > $CHART_FILE
+    setVersion $RELEASE_VERSION
 
-    git add . > /dev/null 2>&1
-    git commit -m "release $RELEASE_VERSION" > /dev/null 2>&1
-    git tag "v$RELEASE_VERSION" > /dev/null 2>&1
-    git push > /dev/null 2>&1
-    git push --tags > /dev/null 2>&1
+    applyChanges "release $RELEASE_VERSION" $RELEASE_VERSION
 
-    CHART_CONTENT="$(cat $CHART_FILE)"
-    echo -n "$CHART_CONTENT" \
-      | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
-      > $CHART_FILE
+    setVersion $NEXT_RELEASE_BRANCH_VERSION
 
-    git add . > /dev/null 2>&1
-    git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]" > /dev/null 2>&1
-    git push > /dev/null 2>&1
-    echo "tagged $RELEASE_VERSION"
+    applyChanges "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]"
+
     exit 0
     ;;
 
   rc)
-    if git log -1 --pretty=%s | grep -q '\[skip ci\]'; then
-      # force empty commit so that tag doesn't point at a "[skip ci]" commit
-      git commit --allow-empty -m 'trigger ci' > /dev/null 2>&1
-    fi
+    setVersion $VERSION
 
-    git tag "v$VERSION" > /dev/null 2>&1
+    applyChanges "release $VERSION" $VERSION
 
     NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.$PATCH-rc.$((PRE+1))"
 
-    CHART_CONTENT="$(cat $CHART_FILE)"
-    echo -n "$CHART_CONTENT" \
-      | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
-      > $CHART_FILE
+    setVersion $NEXT_RELEASE_BRANCH_VERSION
 
-    git add . > /dev/null 2>&1
-    git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]" > /dev/null 2>&1
-    git push > /dev/null 2>&1
-    git push --tags > /dev/null 2>&1
-    echo "tagged v$VERSION"
+    applyChanges "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]"
+
     exit 0
     ;;
 esac
