wip

diff --git a/release-docker-image-codefresh b/release-docker-image-codefresh
--- a/release-docker-image-codefresh
+++ b/release-docker-image-codefresh
@@ -44,13 +44,81 @@ case "$RELEASE_LEVEL" in
     exit 0
     ;;
   *)
-    echo "ERROR: Specify release level of 'pre', 'patch', 'minor', 'major', or 'rc'" >&2
+    if [ -n "$1" ]; then
+      echo "ERROR: specify release level of 'pre', 'patch', 'minor', 'major', or 'rc'" >&2
+    fi
     usage
     exit 1
     ;;
 esac
 
+echo "checking required preconditions"
+
+git pull > /dev/null 2>&1
+
+if ! git diff --exit-code --no-patch > /dev/null 2>&1; then
+  echo 'ERROR: you have modified tracked files; only release from clean directories!' >&2
+  exit 3
+else
+  echo 'INFO: no modified tracked files'
+fi
+
+if ! git diff --cached --exit-code --no-patch > /dev/null 2>&1; then
+  echo 'ERROR: you have cached modified tracked files; only release from clean directories!' >&2
+  exit 3
+else
+  echo 'INFO: no cached modified tracked files'
+fi
+
+if [ -n "$(git status -s)" ]; then
+  echo 'ERROR: You have unignored untracked files; only release from clean directories!' >&2
+  exit 3
+else
+  echo 'INFO: no unignored untracked files'
+fi
+
+BRANCH="$(git status | head -n 1 | awk '{ print $3 }')"
+if [[ ! "$BRANCH" =~ ^(master|v[0-9]{1,}\.[0-9]{1,})$ ]]; then # it is not a master or a release branch
+  echo 'ERROR: you can only release from the master branch or release branches (vmajor.minor)!' >&2
+  exit 3
+else
+  echo "INFO: on branch $BRANCH, from which releases are allowed"
+fi
+
+if ! git diff --exit-code -no-patch $BRANCH $ORIGIN/$BRANCH > /dev/null 2>&1; then
+  echo "ERROR: Local branch $BRANCH differs from remote branch $ORIGIN/$BRANCH" >&2
+  exit 3
+else
+  echo "INFO: no differences between local & remote branch $BRANCH"
+fi
+
+if [ "$BRANCH" == "$MASTER" ]; then
+  case "$RELEASE_LEVEL" in
+    pre|rc)
+      # ok
+      ;;
+    *)
+      echo "ERROR: only 'pre' or 'rc' releases are permitted from the $MASTER branch." >&2
+      exit 6
+      ;;
+  esac
+else # this is a release branch
+  case "$RELEASE_LEVEL" in
+      rc|patch|minor|major)
+        # ok
+        ;;
+      *)
+        echo "ERROR: only 'rc', 'patch', 'minor', or 'major' releases are permitted from a release branch." >&2
+        exit 7
+        ;;
+  esac
+fi
+
+echo "INFO: ok to proceed with $RELEASE_LEVEL from branch $BRANCH"
+
 CODEFRESH_YML=${CODEFRESH_YML:-codefresh.yml}
+
+echo "INFO: determining build step names from $CODEFRESH_YML"
 
 if [ -n "$DOCKER_BUILD_STEP_NAMES" ]; then
   DOCKER_BUILD_STEP_NAMES="$(echo -n "$DOCKER_BUILD_STEP_NAMES" | tr "," " ")" # replace commas with spaces
@@ -63,28 +131,15 @@ if [ -z "$FIRST_DOCKER_BUILD_STEP_NAME" ]; then
   exit 13
 fi
 
+echo "INFO: determining push step names from $CODEFRESH_YML"
+
 if [ -n "$DOCKER_PUSH_STEP_NAMES" ]; then
   DOCKER_PUSH_STEP_NAMES="$(echo -n "$DOCKER_PUSH_STEP_NAMES" | tr "," " ")" # replace commas with spaces
 else
   DOCKER_PUSH_STEP_NAMES="$(cat "$CODEFRESH_YML" | docker run --rm -i matthewadams12/ymlx 'Object.keys(this.steps).filter(it => this.steps[`${it}`].type === "push").join(" ")')"
 fi
 
-git pull > /dev/null 2>&1
-
-if ! git diff --exit-code --no-patch > /dev/null 2>&1; then
-  echo 'ERROR: You have modified tracked files; only release from clean directories!' >&2
-  exit 3
-fi
-
-if ! git diff --cached --exit-code --no-patch > /dev/null 2>&1; then
-  echo 'ERROR: You have cached modified tracked files; only release from clean directories!' >&2
-  exit 3
-fi
-
-if [ -n "$(git status -s)" ]; then
-  echo 'ERROR: You have unignored untracked files; only release from clean directories!' >&2
-  exit 3
-fi
+echo "INFO: determining current version from $CODEFRESH_YML..."
 
 VERSION="$(cat "$CODEFRESH_YML" | docker run --rm -i matthewadams12/ymlx "this.steps['$FIRST_DOCKER_BUILD_STEP_NAME'].tag")"
 if [[ ! "$VERSION" =~ \-(pre|rc)\.[0-9]{1,}$ ]]; then
@@ -92,38 +147,7 @@ if [[ ! "$VERSION" =~ \-(pre|rc)\.[0-9]{1,}$ ]]; then
   exit 3
 fi
 
-BRANCH="$(git status | head -n 1 | awk '{ print $3 }')"
-if [[ ! "$BRANCH" =~ ^(master|v[0-9]{1,}\.[0-9]{1,})$ ]]; then # it is not a master or a release branch
-  echo 'ERROR: You can only release from the master branch or release branches (vmajor.minor)!' >&2
-  exit 3
-fi
-
-if ! git diff --exit-code -no-patch $BRANCH $ORIGIN/$BRANCH > /dev/null 2>&1; then
-  echo "ERROR: Local branch $BRANCH differs from remote branch $ORIGIN/$BRANCH" >&2
-  exit 3
-fi
-
-if [ "$BRANCH" == "$MASTER" ]; then
-  case "$RELEASE_LEVEL" in
-    pre|rc)
-      # ok
-      ;;
-    *)
-      echo "ERROR: Only 'pre' or 'rc' releases are permitted from the $MASTER branch." >&2
-      exit 6
-      ;;
-  esac
-else # this is a release branch
-  case "$RELEASE_LEVEL" in
-      rc|patch|minor|major)
-        # ok
-        ;;
-      *)
-        echo "ERROR: Only 'rc', 'patch', 'minor', or 'major' releases are permitted from a release branch." >&2
-        exit 7
-        ;;
-  esac
-fi
+echo "INFO: current version is $VERSION"
 
 setVersion() {
   V=$1
@@ -167,8 +191,10 @@ apply() {
 
 if [ "$BRANCH" == "$MASTER" ]; then # this will be either an rc, resulting in a new release branch, or a pre
   if [[ ! "$VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})\.0\-pre\.([0-9]{1,})$ ]]; then
-    echo "ERROR: The version does not match the format of major.minor.0-pre.n required in the $MASTER branch." >&2
+    echo "ERROR: the version does not match the format of major.minor.0-pre.n required in the $MASTER branch." >&2
     exit 8
+  else
+    echo "INFO: version $VERSION matches expected format for branch $BRANCH"
   fi
 
   # create release branch
@@ -242,8 +268,10 @@ fi
 # If we get this far, we are releasing something from a release branch.
 
 if [[ ! "$VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})\.([0-9]{1,})\-rc\.([0-9]{1,})$ ]]; then
-  echo "ERROR: The version does not match the format of major.minor.patch-rc.n required in the release branch." >&2
+  echo "ERROR: the version does not match the format of major.minor.patch-rc.n required in the release branch." >&2
   exit 8
+else
+    echo "INFO: version $VERSION matches expected format for branch $BRANCH"
 fi
 MAJOR=${BASH_REMATCH[1]}
 MINOR=${BASH_REMATCH[2]}
@@ -257,21 +285,24 @@ case "$RELEASE_LEVEL" in
     # A major release is the same as a minor release, only that the minor version is 0.
 
     if [ $RELEASE_LEVEL == major ] && [ $MINOR != 0 ]; then
-      echo "ERROR: This branch is not prepared for a major release because the minor version is $MINOR, not 0." >&2
+      echo "ERROR: this branch is not prepared for a major release because the minor version is $MINOR, not 0." >&2
       exit 10
     else
+      echo "INFO: branch $BRANCH is prepared for a major release"
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-rc.0"
     fi
     if [ $RELEASE_LEVEL == minor ] && [ $PATCH != 0 ]; then
-      echo "ERROR: A minor release has already been performed in this release branch; only patch releases are allowed here now." >&2
+      echo "ERROR: a minor release has already been performed in this release branch; only patch releases are allowed here now." >&2
       exit 11
     else
+      echo "INFO: no minor releases have been performed yet in branch $BRANCH"
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-rc.0"
     fi
     if [ $RELEASE_LEVEL == patch ] && [ $PATCH == 0 ]; then
-      echo "ERROR: You must release a minor release before releasing a patch in this release branch." >&2
+      echo "ERROR: you must release a minor release before releasing a patch in this release branch." >&2
       exit 12
     else
+      echo "INFO: no minor releases have occurred yet from branch $BRANCH"
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.$((PATCH+1))-rc.0"
     fi
 
