update release

diff --git a/release b/release
--- a/release
+++ b/release
@@ -216,7 +216,7 @@ case "$RELEASE_LEVEL" in
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-rc.0"
     fi
     if [ $RELEASE_LEVEL == minor ] && [ $PATCH != 0 ]; then
-      echo "ERROR: A minor release has already been performed in this branch; only patch releases are allowed now in this release branch." >&2
+      echo "ERROR: A minor release has already been performed in this release branch; only patch releases are allowed here now." >&2
       exit 11
     else
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-rc.0"
