update docker release script

diff --git a/release-docker-image-codefresh b/release-docker-image-codefresh
--- a/release-docker-image-codefresh
+++ b/release-docker-image-codefresh
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# This script implements the release branch workflow for helm charts.
+# This script implements the release branch workflow for docker images built by codefresh.io.
 #
 # Requirements:
 # git
@@ -16,6 +16,16 @@ if on release branch: release major|minor|patch|pre <chart>
 
 where:
   <chart> is the name of the chart
+
+optional supported environment variables:
+
+variable                  description
+--------                  -----------
+ORIGIN                    name of git remote, default 'origin'
+MASTER                    name of master branch, default 'master'
+CODEFRESH_YML             name of codefresh.yml file, default 'codefresh.yml'
+DOCKER_BUILD_STEP_NAMES   comma-separated list of build step names, defaults from file \$CODEFRESH_YML
+DOCKER_PUSH_STEP_NAMES    comma-separated list of push step names, defaults from file \$CODEFRESH_YML
 EOF
 }
 
@@ -42,8 +52,23 @@ case "$RELEASE_LEVEL" in
 esac
 
 CODEFRESH_YML=${CODEFRESH_YML:-codefresh.yml}
-DOCKER_BUILD_STEP_NAME=${DOCKER_BUILD_STEP_NAME:-BuildingDockerImage}
-DOCKER_PUSH_STEP_NAME=${DOCKER_PUSH_STEP_NAME:-PushingToDockerRegistry}
+
+if [ -z "$DOCKER_BUILD_STEP_NAMES" ]; then
+  DOCKER_BUILD_STEP_NAMES="$(echo -n "$DOCKER_BUILD_STEP_NAMES" | tr "," " ")" # replace commas with spaces
+else
+  DOCKER_BUILD_STEP_NAMES="$(cat "$CODEFRESH_YML" | docker run --rm -i matthewadams12/ymlx 'Object.keys(this.steps).filter(this.steps[`${it}`].type === "build").join(" ")')"
+fi
+FIRST_DOCKER_BUILD_STEP_NAME="$(echo -n "$DOCKER_BUILD_STEP_NAMES" | awk '{print $1}')"
+if [ -z "$FIRST_DOCKER_BUILD_STEP_NAME" ]; then
+  echo "ERROR: no Docker build steps found in file $CODEFRESH_YML" >&2
+  exit 13
+fi
+
+if [ -n "$DOCKER_PUSH_STEP_NAMES" ]; then
+  DOCKER_PUSH_STEP_NAMES="$(echo -n "$DOCKER_PUSH_STEP_NAMES" | tr "," " ")" # replace commas with spaces
+else
+  DOCKER_PUSH_STEP_NAMES="$(cat "$CODEFRESH_YML" | docker run --rm -i matthewadams12/ymlx 'Object.keys(this.steps).filter(it => this.steps[`${it}`].type === "push").join(" ")')"
+fi
 
 git pull > /dev/null 2>&1
 
@@ -62,7 +87,7 @@ if [ -n "$(git status -s)" ]; then
   exit 3
 fi
 
-VERSION="$(cat "$CODEFRESH_YML" | docker run --rm -i matthewadams12/ymlx "this.steps['$DOCKER_PUSH_STEP_NAME'].tag")"
+VERSION="$(cat "$CODEFRESH_YML" | docker run --rm -i matthewadams12/ymlx "this.steps['$FIRST_DOCKER_BUILD_STEP_NAME'].tag")"
 if [[ ! "$VERSION" =~ \-(pre|rc)\.[0-9]{1,}$ ]]; then
   echo 'ERROR: repository is in an inconsistent state: version does NOT end in a prerelease suffix!' >&2
   exit 3
@@ -101,7 +126,7 @@ else # this is a release branch
   esac
 fi
 
-if [ "$BRANCH" == "$MASTER" ]; then
+if [ "$BRANCH" == "$MASTER" ]; then # this will be either an rc, resulting in a new release branch or a prerelease
   if [[ ! "$VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})\.0\-pre\.([0-9]{1,})$ ]]; then
     echo "ERROR: The version does not match the format of major.minor.0-pre.n required in the $MASTER branch." >&2
     exit 8
@@ -120,10 +145,12 @@ if [ "$BRANCH" == "$MASTER" ]; then
 
       NEW_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.0-rc.0"
 
-      CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
-      echo -n "$CODEFRESH_YML_CONTENT" \
-        | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$DOCKER_PUSH_STEP_NAME'].tag = '$NEW_RELEASE_BRANCH_VERSION'; return it; }" \
-        > "$CODEFRESH_YML"
+      for step in $DOCKER_PUSH_STEP_NAMES; do
+        CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
+        echo -n "$CODEFRESH_YML_CONTENT" \
+          | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$step'].tag = '$NEW_RELEASE_BRANCH_VERSION'; return it; }" \
+          > "$CODEFRESH_YML"
+      done
 
       git add . > /dev/null 2>&1
       git commit -m "release $NEW_RELEASE_BRANCH_VERSION" > /dev/null 2>&1
@@ -137,10 +164,17 @@ if [ "$BRANCH" == "$MASTER" ]; then
       # advance master version
       NEXT_VERSION="$MAJOR.$(($MINOR+1)).0-pre.0"
 
-      CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
-      echo -n "$CODEFRESH_YML_CONTENT" \
-        | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$DOCKER_PUSH_STEP_NAME'].tag = '$NEXT_VERSION'; return it; }" \
-        > "$CODEFRESH_YML"
+      for step in $DOCKER_BUILD_STEP_NAMES; do
+        CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
+        echo -n "$CODEFRESH_YML_CONTENT" \
+          | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$step'].tag = '$NEXT_VERSION'; return it; }" \
+          > "$CODEFRESH_YML"
+      done
+      for step in $DOCKER_PUSH_STEP_NAMES; do
+        echo -n "$CODEFRESH_YML_CONTENT" \
+          | docker run --rm -i matthewadams12/ymlx "it => { delete it.steps['$step'].tag; return it; }" \
+          > "$CODEFRESH_YML"
+      done
 
       git add . > /dev/null 2>&1
       git commit -m "bump to $NEXT_VERSION [skip ci]" > /dev/null 2>&1
@@ -150,10 +184,12 @@ if [ "$BRANCH" == "$MASTER" ]; then
       git checkout $NEW_RELEASE_BRANCH > /dev/null 2>&1
       NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.0-rc.1"
 
-      CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
-      echo -n "$CODEFRESH_YML_CONTENT" \
-        | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$DOCKER_PUSH_STEP_NAME'].tag = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
-        > "$CODEFRESH_YML"
+      for step in $DOCKER_BUILD_STEP_NAMES; do
+        CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
+        echo -n "$CODEFRESH_YML_CONTENT" \
+          | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$step'].tag = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
+          > "$CODEFRESH_YML"
+      done
 
       git add . > /dev/null 2>&1
       git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]" > /dev/null 2>&1
@@ -168,10 +204,12 @@ if [ "$BRANCH" == "$MASTER" ]; then
       RELEASED_VERSION="$VERSION"
       NEXT_VERSION=$MAJOR.$MINOR.$PATCH-pre.$((PRE+1))
 
-      CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
-      echo -n "$CODEFRESH_YML_CONTENT" \
-        | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$DOCKER_PUSH_STEP_NAME'].tag = '$NEXT_VERSION'; return it; }" \
-        > "$CODEFRESH_YML"
+      for step in $DOCKER_BUILD_STEP_NAMES; do
+        CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
+        echo -n "$CODEFRESH_YML_CONTENT" \
+          | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$step'].tag = '$NEXT_VERSION'; return it; }" \
+          > "$CODEFRESH_YML"
+      done
 
       git add . > /dev/null 2>&1
       git commit -m "bump to $NEXT_VERSION [skip ci]" > /dev/null 2>&1
@@ -221,10 +259,12 @@ case "$RELEASE_LEVEL" in
 
     RELEASE_VERSION="$MAJOR.$MINOR.$PATCH"
 
-    CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
-    echo -n "$CODEFRESH_YML_CONTENT" \
-      | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$DOCKER_PUSH_STEP_NAME'].tag = '$RELEASE_VERSION'; return it; }" \
-      > "$CODEFRESH_YML"
+    for step in $DOCKER_BUILD_STEP_NAMES; do
+      CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
+      echo -n "$CODEFRESH_YML_CONTENT" \
+        | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$step'].tag = '$RELEASE_VERSION'; return it; }" \
+        > "$CODEFRESH_YML"
+    done
 
     git add . > /dev/null 2>&1
     git commit -m "release $RELEASE_VERSION" > /dev/null 2>&1
@@ -232,10 +272,12 @@ case "$RELEASE_LEVEL" in
     git push > /dev/null 2>&1
     git push --tags > /dev/null 2>&1
 
-    CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
-    echo -n "$CODEFRESH_YML_CONTENT" \
-      | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$DOCKER_PUSH_STEP_NAME'].tag = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
-      > "$CODEFRESH_YML"
+    for step in $DOCKER_BUILD_STEP_NAMES; do
+      CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
+      echo -n "$CODEFRESH_YML_CONTENT" \
+        | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$step'].tag = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
+        > "$CODEFRESH_YML"
+    done
 
     git add . > /dev/null 2>&1
     git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]" > /dev/null 2>&1
@@ -249,10 +291,12 @@ case "$RELEASE_LEVEL" in
 
     NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.$PATCH-rc.$((PRE+1))"
 
-    CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
-    echo -n "$CODEFRESH_YML_CONTENT" \
-      | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$DOCKER_PUSH_STEP_NAME'].tag = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
-      > "$CODEFRESH_YML"
+    for step in $DOCKER_BUILD_STEP_NAMES; do
+      CODEFRESH_YML_CONTENT="$(cat "$CODEFRESH_YML")"
+      echo -n "$CODEFRESH_YML_CONTENT" \
+        | docker run --rm -i matthewadams12/ymlx "it => { it.steps['$step'].tag = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
+        > "$CODEFRESH_YML"
+    done
 
     git add . > /dev/null 2>&1
     git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]" > /dev/null 2>&1
